apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-hop
  namespace: dev-athena
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-hop
  template:
    metadata:
      labels:
        app: apache-hop
    spec:
      containers:
      - name: hop
        image: tiagolinhares015/apache_hop_ssh_java:latest
        ports:
        - containerPort: 8181
        - containerPort: 22
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Gerar chaves de host SSH
            ssh-keygen -A
            # Iniciar o serviço SSH
            /usr/sbin/sshd &
            # Iniciar o Hop Server usando o arquivo de configuração do ConfigMap
            exec /opt/hop/hop-server.sh /opt/hop/hop-server-config.xml
        volumeMounts:
        - name: hop-config
          mountPath: /opt/hop/hop-server-config.xml
          subPath: hop-server-config.xml
        - name: hop-files
          mountPath: /files
        - name: git-ssh-key
          mountPath: /root/.ssh
          readOnly: true
      volumes:
      - name: hop-config
        configMap:
          name: hop-server-config
      - name: hop-files
        hostPath:
          path: /opt/dags
      - name: git-ssh-key
        secret:
          secretName: git-ssh-key
      restartPolicy: Always
