apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-hop
  namespace: dev-athena
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-hop
  template:
    metadata:
      labels:
        app: apache-hop
    spec:
      containers:
      - name: hop
        image: tiagolinhares015/apache_hop_ssh:latest
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 8080
        - containerPort: 22
        env:
          - name: HOP_PROJECT_NAME
            value: "athena"
          - name: HOP_PROJECT_FOLDER
            value: "/opt/dags"
          - name: HOP_PROJECT_CONFIG
            value: "/opt/dags/project-config.json"
          - name: HOP_METADATA_FOLDER
            value: "/opt/dags/metadata"
          - name: HOP_FILE_PATH
            value: "/opt/dags"
          - name: HOP_LOG_LEVEL
            value: "Detailed"
          - name: HOP_RUN_CONFIG
            value: "local"
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Gerar chaves de host SSH
            ssh-keygen -A
            # Iniciar o serviço SSH e manter o container rodando
            /usr/sbin/sshd -D
        volumeMounts:
        - name: hop-files
          mountPath: /files
        - name: git-ssh-key
          mountPath: /root/.ssh
          readOnly: true
      volumes:
      - name: hop-files
        hostPath:
          path: /opt/dags
      - name: git-ssh-key
        secret:
          secretName: git-ssh-key
      restartPolicy: Always
