apiVersion: v1
kind: Service
metadata:
  name: hop-server-service
  namespace: dev-athena
spec:
  type: NodePort
  selector:
    app: apache-hop
  ports:
    - port: 8181
      targetPort: 8181
      nodePort: 30181