apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: dev-athena
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: airflow-web
