apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: dev-athena
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30001
      protocol: TCP
  selector:
    app: postgres
